version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - medical_booking_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: medical_booking_server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - medical_booking_network
    environment:
      - MONGO_URI=mongodb://mongo:27017/medical_booking

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: medical_booking_client
    ports:
      - "3000:3000"
    networks:
      - medical_booking_network

volumes:
  mongo_data:

networks:
  medical_booking_network: